### ISSUE TITLE
Env Description

### ISSUE THREAD

**Issue by TheODDYSEY** [prankush-tech/Agency-Automation-Tools#2]
what are the env and tech needed to run this app

**Comment by prankush-tech** [comment]
> what are the env and tech needed to run this app

You can chek its functionality here https://prankush-agency.vercel.app/ 
The Supabase server is free as of now, usually gets cold ( Hence sometimes fetches no data from supabase ) . Needs a hot reload from the dashboard.

Meanwhile if you wanted to run this locally you need the .env file with

NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

DATABASE_URL=

NEXT_PUBLIC_URL=https://prankush-agency.vercel.app
NEXT_PUBLIC_DOMAIN=localhost:3000
NEXT_PUBLIC_SCHEME=https://

NEXT_PUBLIC_GOOGLE_SCOPES=https://www.googleapis.com/auth/drive
NEXT_PUBLIC_OAUTH2_ENDPOINT=https://accounts.google.com/o/oauth2/v2/auth

NEXT_PUBLIC_UPLOAD_CARE_CSS_SRC=
NEXT_PUBLIC_UPLOAD_CARE_SRC_PACKAGE=

DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_TOKEN= # not necessary
DISCORD_PUBLICK_KEY=
NEXT_PUBLIC_DISCORD_REDIRECT=

NOTION_API_SECRET=
NOTION_CLIENT_ID=
NOTION_REDIRECT_URI=
NEXT_PUBLIC_NOTION_AUTH_URL=

SLACK_SIGNING_SECRET=
SLACK_BOT_TOKEN=
SLACK_APP_TOKEN=
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=
SLACK_REDIRECT_URI=
NEXT_PUBLIC_SLACK_REDIRECT=

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
OAUTH2_REDIRECT_URI=
NGROK_URI=
CRON_JOB_KEY=
STRIPE_SECRET=
